<?php
// In this file, we only create HTML form. Form data processing is performed in the file submit.php.

// Include script file.
require_once '../../fb/fb_index.php';

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="Content-Language" content="en" />

  <title>Feedback</title>
  <meta name="keywords" content="ketwords" />

</head>
<body>

<?php

// Сreate an object of class.
$fb = new Fb();

/* Set validation rules of HTML form fields by function addName().
 Note: validation is used only for the fields specified in the e-mail template file fb/templ_mail.php.
                                                                                                     
$fb->addName($name, $type, $err, $request, $max_len, $min_len, $type_html);

Parameters:

$name -   name of the form element (<input type="text" name="phone" />, <select name="phone"> etc.) 
          если name = emailto, 0то на указанный в значении поля адрес будет выслано это письмо
          If $name = "emailto", the message will be sent to the email address specified in the field value. 

$type -   type of input data. Available values: 'numb' - numbers; 'email' - email address; '' - not checked. 
          The default value is ''.
 
$err -    error message. 
          The default value is ''.
          Note: the default error message can be changed in the file Fb.php (Fb::ERR_MSG)
 
$request - field is required. 
          Available values:  0 - not required, 1 - required
          The default value is 0.
          
$max_len - maximum number of characters.  
          The default value is 0 (undefined).   
    
$min_len - minimum number of characters.  
          The default value is 0 (undefined).   
     
$type_html - HTML form element. Set the parameter if you want to generate a HTML form.
            Available types: text, select, textarea.
            The default value is 'text'.
               
            For example:
                        
            example 1:  element 'select' with a drop-down list.
                       
                        $element['select']    = Array('support@domain.com' => 'Support',    // value of the item => name of the item
                                                      'manager@domain.com' => 'Manager');   // value of the item => name of the item
                        $element['title']     = 'Select subject';        // Field title. The default value is a fild name.
   
            example 2:  element 'textarea' 
          
                        $element['textarea']  = 'Text abc';
                        $element['title']     = 'Input text';

*/

// Add fields to the form.
// the field "Name"
$fb->addName(
    'name',
    '',
    '',
    0,
    0,
    0,
    'text'
);

// the field "Phone"
$fb->addName('phone', 'numb', 'Phone is wrong!', 0, 10, 0, 'text');

// the field "E-Mail"
$element_email['text'] = '';
$element_email['title'] = 'E-Mail';
$fb->addName('email','email', '', 1, 0, 0, $element_email);

// the field "Subject"
$element['select'] = Array (
                        'aleksandern08@gmail.com' => 'Support',
                        'fbexample47@gmail.com' => 'Manager',
                        );
$element['title'] = 'Subject';
$fb->addName(
    'emailto',
    'email',
    '',
    0,
    0,
    0,
    $element
);

// the field "Text"
$fb->addName('text','numb', '', 1, 0, 0, 'textarea');

// Enable captcha (only when HTML form generated by the script itself or when checked data from html form).
// Captcha settings fb/app/kcaptcha/kcaptcha_config.php. 
$fb->captcha();

// The position of the form (left or right). The default value is 'left'.
// $fb->positionForm('right');

// Create HTML form, if necessary. Specify the form processing script as a parameter. 
$fb->displayForm('submit.php');

// Show HTML form.
$fb->finish();

?>
</body>
</html>
