<?php
// Data processing HTML form that was created in the file index.html

// Include script file.
require_once '../../fb/fb_index.php';

// Сreate an object of class.
$fb = new Fb();

/* Set validation rules of HTML form fields by function addName().
 Note: validation is used only for the fields specified in the e-mail template file fb/templ_mail.php.
                                                                                                     
$fb->addName($name, $type, $err, $request, $max_len, $min_len, $type_html);

Parameters:

$name -   name of the form element (<input type="text" name="phone" />, <select name="phone"> etc.) 
          если name = emailto, 0то на указанный в значении поля адрес будет выслано это письмо
          If $name = "emailto", the message will be sent to the email address specified in the field value. 

$type -   type of input data. Available values: 'numb' - numbers; 'email' - email address; '' - not checked. 
          The default value is ''.
 
$err -    error message. 
          The default value is ''.
          Note: the default error message can be changed in the file Fb.php (Fb::ERR_MSG)
 
$request - field is required. 
          Available values:  0 - not required, 1 - required
          The default value is 0.
          
$max_len - maximum number of characters.  
          The default value is 0 (undefined).   
    
$min_len - minimum number of characters.  
          The default value is 0 (undefined).   
     
$type_html - HTML form element. Set the parameter if you want to generate a HTML form.
            Available types: text, select, textarea.
            The default value is 'text'.
           
            For example:
                        
            example 1:  element 'select' with a drop-down list.
                       
                        $element['select']    = Array('support@domain.com' => 'Support',    // value of the item => name of the item
                                                      'manager@domain.com' => 'Manager');   // value of the item => name of the item
                        $element['title']     = 'Select subject';        // Field title. The default value is a fild name.
   
            example 2:  element 'textarea' 
          
                        $element['textarea']  = 'Text abc';
                        $element['title']     = 'Input text';

*/


// Validation rule for the field "Phone"
$fb->addName( 'phone', 'numb', 'Phone is wrong!', 0, 10, 0, 'text');

// Validation rule for the field "E-Mail"
$fb->addName('email','email', '', 1);

// Validation rule for the field "Text"
$fb->addName('text','', '', 1);

// The destination address.
$fb->mail->_to('aleksandern08@gmail.com');

// The sender address. The second parameter is optional.
$fb->mail->_from('fbexample47@gmail.com', 'FeedBack from My Site!');

// Use this method with parameter 'false' to disable the PHP function mail().
$fb->mail->nativeMail(false);

// If you disable the standard PHP function mail(), you should set up a PHP script to send mail.

$fb->mail->setting->host_name="smtp.gmail.com";  /* Change this variable to the address of the SMTP server to relay, like "smtp.myisp.com" */
$fb->mail->setting->host_port=465;  /* Change this variable to the port of the SMTP server to use, like 465 */
$fb->mail->setting->ssl=1;   /* OpenSSL module is required (http:www.php.net/openssl). Change this variable if the SMTP server requires an secure connection using SSL */
$fb->mail->setting->start_tls=0;   /* Change this variable if the SMTP server requires security by starting TLS */ 
$fb->mail->setting->realm="gmail.com";  /* Set to the authetication realm, usually the authentication user e-mail domain */
$fb->mail->setting->user = "fbexample47";   /* Set to the user name if the server requires authetication */
$fb->mail->setting->password =  "fbexample26";                 /* Set to the authetication password */


// Enable captcha (only when HTML form generated by the script itself or when checked data from html form).
// Captcha settings fb/app/kcaptcha/kcaptcha_config.php.
//$fb->captcha();

// Create HTML form, if necessary. Specify the form processing script as a parameter.
//$fb->displayForm('submit.php');

// Data processing.
$fb->finish();


